/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorResponse from './model/ErrorResponse';
import LoginReq from './model/LoginReq';
import RegisterReq from './model/RegisterReq';
import UserInfoReply from './model/UserInfoReply';
import UserSearchReq from './model/UserSearchReq';
import UserApiApi from './api/UserApiApi';


/**
* type desc here.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TypeTitleHere = require('index'); // See note below*.
* var xxxSvc = new TypeTitleHere.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TypeTitleHere.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TypeTitleHere.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TypeTitleHere.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version type version here
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The LoginReq model constructor.
     * @property {module:model/LoginReq}
     */
    LoginReq,

    /**
     * The RegisterReq model constructor.
     * @property {module:model/RegisterReq}
     */
    RegisterReq,

    /**
     * The UserInfoReply model constructor.
     * @property {module:model/UserInfoReply}
     */
    UserInfoReply,

    /**
     * The UserSearchReq model constructor.
     * @property {module:model/UserSearchReq}
     */
    UserSearchReq,

    /**
    * The UserApiApi service constructor.
    * @property {module:api/UserApiApi}
    */
    UserApiApi
};
