/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterReq model module.
 * @module model/RegisterReq
 * @version type version here
 */
class RegisterReq {
    /**
     * Constructs a new <code>RegisterReq</code>.
     * @alias module:model/RegisterReq
     * @param mobile {String} 
     * @param password {String} 
     * @param username {String} 
     */
    constructor(mobile, password, username) { 
        
        RegisterReq.initialize(this, mobile, password, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mobile, password, username) { 
        obj['mobile'] = mobile;
        obj['password'] = password;
        obj['username'] = username;
    }

    /**
     * Constructs a <code>RegisterReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterReq} obj Optional instance to populate.
     * @return {module:model/RegisterReq} The populated <code>RegisterReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterReq();

            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegisterReq</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegisterReq</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RegisterReq.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['mobile'] && !(typeof data['mobile'] === 'string' || data['mobile'] instanceof String)) {
            throw new Error("Expected the field `mobile` to be a primitive type in the JSON string but got " + data['mobile']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

RegisterReq.RequiredProperties = ["mobile", "password", "username"];

/**
 * @member {String} mobile
 */
RegisterReq.prototype['mobile'] = undefined;

/**
 * @member {String} password
 */
RegisterReq.prototype['password'] = undefined;

/**
 * @member {String} username
 */
RegisterReq.prototype['username'] = undefined;






export default RegisterReq;

