/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserInfoReply model module.
 * @module model/UserInfoReply
 * @version type version here
 */
class UserInfoReply {
    /**
     * Constructs a new <code>UserInfoReply</code>.
     * @alias module:model/UserInfoReply
     * @param age {Number} 
     * @param birthday {String} 
     * @param description {String} 
     * @param name {String} 
     * @param tag {Array.<String>} 
     * @param tags {Array.<Array.<String>>} 
     */
    constructor(age, birthday, description, name, tag, tags) { 
        
        UserInfoReply.initialize(this, age, birthday, description, name, tag, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, age, birthday, description, name, tag, tags) { 
        obj['age'] = age;
        obj['birthday'] = birthday;
        obj['description'] = description;
        obj['name'] = name;
        obj['tag'] = tag;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>UserInfoReply</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserInfoReply} obj Optional instance to populate.
     * @return {module:model/UserInfoReply} The populated <code>UserInfoReply</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserInfoReply();

            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
            if (data.hasOwnProperty('birthday')) {
                obj['birthday'] = ApiClient.convertToType(data['birthday'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], ['String']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [['String']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserInfoReply</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserInfoReply</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserInfoReply.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['birthday'] && !(typeof data['birthday'] === 'string' || data['birthday'] instanceof String)) {
            throw new Error("Expected the field `birthday` to be a primitive type in the JSON string but got " + data['birthday']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tag'])) {
            throw new Error("Expected the field `tag` to be an array in the JSON data but got " + data['tag']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

UserInfoReply.RequiredProperties = ["age", "birthday", "description", "name", "tag", "tags"];

/**
 * @member {Number} age
 */
UserInfoReply.prototype['age'] = undefined;

/**
 * @member {String} birthday
 */
UserInfoReply.prototype['birthday'] = undefined;

/**
 * @member {String} description
 */
UserInfoReply.prototype['description'] = undefined;

/**
 * @member {String} name
 */
UserInfoReply.prototype['name'] = undefined;

/**
 * @member {Array.<String>} tag
 */
UserInfoReply.prototype['tag'] = undefined;

/**
 * @member {Array.<Array.<String>>} tags
 */
UserInfoReply.prototype['tags'] = undefined;






export default UserInfoReply;

