/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserSearchReq model module.
 * @module model/UserSearchReq
 * @version type version here
 */
class UserSearchReq {
    /**
     * Constructs a new <code>UserSearchReq</code>.
     * @alias module:model/UserSearchReq
     * @param keyWord {String}  关键词
     */
    constructor(keyWord) { 
        
        UserSearchReq.initialize(this, keyWord);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, keyWord) { 
        obj['keyWord'] = keyWord;
    }

    /**
     * Constructs a <code>UserSearchReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSearchReq} obj Optional instance to populate.
     * @return {module:model/UserSearchReq} The populated <code>UserSearchReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSearchReq();

            if (data.hasOwnProperty('keyWord')) {
                obj['keyWord'] = ApiClient.convertToType(data['keyWord'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserSearchReq</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserSearchReq</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserSearchReq.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['keyWord'] && !(typeof data['keyWord'] === 'string' || data['keyWord'] instanceof String)) {
            throw new Error("Expected the field `keyWord` to be a primitive type in the JSON string but got " + data['keyWord']);
        }

        return true;
    }


}

UserSearchReq.RequiredProperties = ["keyWord"];

/**
 *  关键词
 * @member {String} keyWord
 */
UserSearchReq.prototype['keyWord'] = undefined;






export default UserSearchReq;

