/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import LoginReq from '../model/LoginReq';
import RegisterReq from '../model/RegisterReq';
import UserInfoReply from '../model/UserInfoReply';

/**
* UserApi service.
* @module api/UserApiApi
* @version type version here
*/
export default class UserApiApi {

    /**
    * Constructs a new UserApiApi. 
    * @alias module:api/UserApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getUserInfo operation.
     * @callback module:api/UserApiApi~getUserInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserInfoReply} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 获取用户信息
     * @param {String} id 
     * @param {module:api/UserApiApi~getUserInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserInfoReply}
     */
    getUserInfo(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getUserInfo");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserInfoReply;
      return this.apiClient.callApi(
        '/api/user/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the login operation.
     * @callback module:api/UserApiApi~loginCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 登录
     * @param {String} appId APPID-TEST
     * @param {module:model/LoginReq} loginReq 
     * @param {module:api/UserApiApi~loginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    login(appId, loginReq, callback) {
      let postBody = loginReq;
      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling login");
      }
      // verify the required parameter 'loginReq' is set
      if (loginReq === undefined || loginReq === null) {
        throw new Error("Missing the required parameter 'loginReq' when calling login");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'appId': appId
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/user/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the register operation.
     * @callback module:api/UserApiApi~registerCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 注册
     * @param {module:model/RegisterReq} registerReq 注册请求结构
     * @param {module:api/UserApiApi~registerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    register(registerReq, callback) {
      let postBody = registerReq;
      // verify the required parameter 'registerReq' is set
      if (registerReq === undefined || registerReq === null) {
        throw new Error("Missing the required parameter 'registerReq' when calling register");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/user/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchUser operation.
     * @callback module:api/UserApiApi~searchUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserInfoReply} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 用户搜索
     * @param {String} keyWord  关键词
     * @param {module:api/UserApiApi~searchUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserInfoReply}
     */
    searchUser(keyWord, callback) {
      let postBody = null;
      // verify the required parameter 'keyWord' is set
      if (keyWord === undefined || keyWord === null) {
        throw new Error("Missing the required parameter 'keyWord' when calling searchUser");
      }

      let pathParams = {
      };
      let queryParams = {
        'keyWord': keyWord
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserInfoReply;
      return this.apiClient.callApi(
        '/api/user/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
