/**
 * type title here
 * type desc here
 *
 * The version of the OpenAPI document: type version here
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TypeTitleHere);
  }
}(this, function(expect, TypeTitleHere) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TypeTitleHere.UserSearchReq();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserSearchReq', function() {
    it('should create an instance of UserSearchReq', function() {
      // uncomment below and update the code to test UserSearchReq
      //var instance = new TypeTitleHere.UserSearchReq();
      //expect(instance).to.be.a(TypeTitleHere.UserSearchReq);
    });

    it('should have the property keyWord (base name: "keyWord")', function() {
      // uncomment below and update the code to test the property keyWord
      //var instance = new TypeTitleHere.UserSearchReq();
      //expect(instance).to.be();
    });

  });

}));
