/*
type title here

type desc here

API version: type version here
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterReq{}

// RegisterReq struct for RegisterReq
type RegisterReq struct {
	Mobile string `json:"mobile"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type _RegisterReq RegisterReq

// NewRegisterReq instantiates a new RegisterReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterReq(mobile string, password string, username string) *RegisterReq {
	this := RegisterReq{}
	this.Mobile = mobile
	this.Password = password
	this.Username = username
	return &this
}

// NewRegisterReqWithDefaults instantiates a new RegisterReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterReqWithDefaults() *RegisterReq {
	this := RegisterReq{}
	return &this
}

// GetMobile returns the Mobile field value
func (o *RegisterReq) GetMobile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value
// and a boolean to check if the value has been set.
func (o *RegisterReq) GetMobileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mobile, true
}

// SetMobile sets field value
func (o *RegisterReq) SetMobile(v string) {
	o.Mobile = v
}

// GetPassword returns the Password field value
func (o *RegisterReq) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterReq) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterReq) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value
func (o *RegisterReq) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RegisterReq) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RegisterReq) SetUsername(v string) {
	o.Username = v
}

func (o RegisterReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mobile"] = o.Mobile
	toSerialize["password"] = o.Password
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *RegisterReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mobile",
		"password",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterReq := _RegisterReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterReq)

	if err != nil {
		return err
	}

	*o = RegisterReq(varRegisterReq)

	return err
}

type NullableRegisterReq struct {
	value *RegisterReq
	isSet bool
}

func (v NullableRegisterReq) Get() *RegisterReq {
	return v.value
}

func (v *NullableRegisterReq) Set(val *RegisterReq) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterReq) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterReq(val *RegisterReq) *NullableRegisterReq {
	return &NullableRegisterReq{value: val, isSet: true}
}

func (v NullableRegisterReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


