/*
type title here

type desc here

API version: type version here
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserSearchReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSearchReq{}

// UserSearchReq struct for UserSearchReq
type UserSearchReq struct {
	//  关键词
	KeyWord string `json:"keyWord"`
}

type _UserSearchReq UserSearchReq

// NewUserSearchReq instantiates a new UserSearchReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSearchReq(keyWord string) *UserSearchReq {
	this := UserSearchReq{}
	this.KeyWord = keyWord
	return &this
}

// NewUserSearchReqWithDefaults instantiates a new UserSearchReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSearchReqWithDefaults() *UserSearchReq {
	this := UserSearchReq{}
	return &this
}

// GetKeyWord returns the KeyWord field value
func (o *UserSearchReq) GetKeyWord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyWord
}

// GetKeyWordOk returns a tuple with the KeyWord field value
// and a boolean to check if the value has been set.
func (o *UserSearchReq) GetKeyWordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyWord, true
}

// SetKeyWord sets field value
func (o *UserSearchReq) SetKeyWord(v string) {
	o.KeyWord = v
}

func (o UserSearchReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSearchReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyWord"] = o.KeyWord
	return toSerialize, nil
}

func (o *UserSearchReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keyWord",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSearchReq := _UserSearchReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSearchReq)

	if err != nil {
		return err
	}

	*o = UserSearchReq(varUserSearchReq)

	return err
}

type NullableUserSearchReq struct {
	value *UserSearchReq
	isSet bool
}

func (v NullableUserSearchReq) Get() *UserSearchReq {
	return v.value
}

func (v *NullableUserSearchReq) Set(val *UserSearchReq) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSearchReq) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSearchReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSearchReq(val *UserSearchReq) *NullableUserSearchReq {
	return &NullableUserSearchReq{value: val, isSet: true}
}

func (v NullableUserSearchReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSearchReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


