/*
type title here

type desc here

API version: type version here
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserInfoReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInfoReply{}

// UserInfoReply struct for UserInfoReply
type UserInfoReply struct {
	Age int32 `json:"age"`
	Birthday string `json:"birthday"`
	Description string `json:"description"`
	Name string `json:"name"`
	Tag []string `json:"tag"`
	Tags [][]string `json:"tags"`
}

type _UserInfoReply UserInfoReply

// NewUserInfoReply instantiates a new UserInfoReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInfoReply(age int32, birthday string, description string, name string, tag []string, tags [][]string) *UserInfoReply {
	this := UserInfoReply{}
	this.Age = age
	this.Birthday = birthday
	this.Description = description
	this.Name = name
	this.Tag = tag
	this.Tags = tags
	return &this
}

// NewUserInfoReplyWithDefaults instantiates a new UserInfoReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInfoReplyWithDefaults() *UserInfoReply {
	this := UserInfoReply{}
	return &this
}

// GetAge returns the Age field value
func (o *UserInfoReply) GetAge() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Age
}

// GetAgeOk returns a tuple with the Age field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetAgeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Age, true
}

// SetAge sets field value
func (o *UserInfoReply) SetAge(v int32) {
	o.Age = v
}

// GetBirthday returns the Birthday field value
func (o *UserInfoReply) GetBirthday() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetBirthdayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Birthday, true
}

// SetBirthday sets field value
func (o *UserInfoReply) SetBirthday(v string) {
	o.Birthday = v
}

// GetDescription returns the Description field value
func (o *UserInfoReply) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *UserInfoReply) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *UserInfoReply) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserInfoReply) SetName(v string) {
	o.Name = v
}

// GetTag returns the Tag field value
func (o *UserInfoReply) GetTag() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetTagOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tag, true
}

// SetTag sets field value
func (o *UserInfoReply) SetTag(v []string) {
	o.Tag = v
}

// GetTags returns the Tags field value
func (o *UserInfoReply) GetTags() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *UserInfoReply) GetTagsOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *UserInfoReply) SetTags(v [][]string) {
	o.Tags = v
}

func (o UserInfoReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInfoReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["age"] = o.Age
	toSerialize["birthday"] = o.Birthday
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["tag"] = o.Tag
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *UserInfoReply) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"age",
		"birthday",
		"description",
		"name",
		"tag",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInfoReply := _UserInfoReply{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInfoReply)

	if err != nil {
		return err
	}

	*o = UserInfoReply(varUserInfoReply)

	return err
}

type NullableUserInfoReply struct {
	value *UserInfoReply
	isSet bool
}

func (v NullableUserInfoReply) Get() *UserInfoReply {
	return v.value
}

func (v *NullableUserInfoReply) Set(val *UserInfoReply) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInfoReply) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInfoReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInfoReply(val *UserInfoReply) *NullableUserInfoReply {
	return &NullableUserInfoReply{value: val, isSet: true}
}

func (v NullableUserInfoReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInfoReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


